# Generated by Django 3.2.12 on 2022-03-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_user_is_blocked_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
